#!/bin/sh -e

each_conf() {
  while read -r f; do
    "$@" "$(basename "$f")"
  done
}

case $1 in
  tmpfiles) each_conf /usr/bin/tmpfiles --create ;;
  *) echo >&2 "  Invalid operation '$1'"; exit 1 ;;
esac

exit 0
