#!/bin/sh

post_upgrade() {
  # return if old package version greater 3.1.2-5...
  (( $(vercmp "$2" '3.1.2-5') > 0 )) && return

  echo ' > For security reasons the rsyncd service protects the system by making'
  echo ' > paths /boot, /etc and /usr read-only. If you need write access use'
  echo ' > rsync via ssh or see the wiki for instructions to override:'
  echo ' > https://wiki.archlinux.org/index.php/Rsync#rsync_daemon'
}
